### PR TITLE
[ticket/12291] Removed smilies_path from smilies' template

### PR DESCRIPTION
**Pull request by s9e**
That should be right but I haven't run the migration so I couldn't test locally.

### CODE REVIEW

**Comment by rxu** [comment]
I'll try testing it locally, thanks a lot.

**Comment by rxu** [comment]
It seems that tests require adjustments too :/

**Comment by s9e** [comment]
Add tests to your branch and I'll see how they fail.

**Comment by rxu** [comment]
The PR has a migration file to update ```smiley_url``` paths for every smiley in the DB by appending the value of ```config['smilies_path']```. The ```smiley_path``` config value itself isn't get updated.
So i guess it requires just updating the paths in fixtures for tests to pass.

**Comment by s9e** [comment]
It makes sense that the fixtures would need to be updated, I wasn't thinking right. I updated my branch with the correct fixtures. c4828b47005138ad80740fc25287df7fc1f476b1

**Comment by rxu** [comment]
@s9e Thanks a lot. ```custom.gif``` path was missing from changes but I've corrected that after cherry-picking your commit. Now tests pass.

**Pull request merged**
